### ISSUE TITLE
Dropdown needs better way of handling outside clicks

### ISSUE THREAD

**Issue by JannKleen** [resmio/mantecao#88]

**Comment by menor** [comment]
- What are the problems with way we do it now?
- What would be a better way to do it?

**Comment by heinburger** [comment]
This was fixed with 1.0.3

**Comment by heinburger** [comment]
we moved from using the `target.closest` to a method that uses the react synthetic events in conjunction with an internal state to figure out if the mouse or touch event is outside of the dropdown
